# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ct_display.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CTDisplay(object):
    def setupUi(self, CTDisplay):
        CTDisplay.setObjectName("CTDisplay")
        CTDisplay.resize(991, 694)
        self.mpl_ct = MplSliceWidget(CTDisplay)
        self.mpl_ct.setGeometry(QtCore.QRect(10, 9, 610, 570))
        self.mpl_ct.setObjectName("mpl_ct")
        self.sliceScrollbar = QtWidgets.QScrollBar(CTDisplay)
        self.sliceScrollbar.setGeometry(QtCore.QRect(630, 30, 16, 471))
        self.sliceScrollbar.setMinimum(1)
        self.sliceScrollbar.setMaximum(120)
        self.sliceScrollbar.setProperty("value", 60)
        self.sliceScrollbar.setOrientation(QtCore.Qt.Vertical)
        self.sliceScrollbar.setObjectName("sliceScrollbar")
        self.displayButton = QtWidgets.QPushButton(CTDisplay)
        self.displayButton.setGeometry(QtCore.QRect(350, 620, 116, 32))
        self.displayButton.setObjectName("displayButton")
        self.pixelsLabel = QtWidgets.QLabel(CTDisplay)
        self.pixelsLabel.setGeometry(QtCore.QRect(930, 210, 60, 16))
        self.pixelsLabel.setObjectName("pixelsLabel")
        self.cubelenLabel = QtWidgets.QLabel(CTDisplay)
        self.cubelenLabel.setGeometry(QtCore.QRect(740, 260, 211, 20))
        self.cubelenLabel.setObjectName("cubelenLabel")
        self.layoutWidget = QtWidgets.QWidget(CTDisplay)
        self.layoutWidget.setGeometry(QtCore.QRect(746, 145, 181, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cubelocLabel = QtWidgets.QLabel(self.layoutWidget)
        self.cubelocLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cubelocLabel.setObjectName("cubelocLabel")
        self.verticalLayout_4.addWidget(self.cubelocLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.xTopLabel = QtWidgets.QLabel(self.layoutWidget)
        self.xTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xTopLabel.setObjectName("xTopLabel")
        self.horizontalLayout_3.addWidget(self.xTopLabel)
        self.yTopLabel = QtWidgets.QLabel(self.layoutWidget)
        self.yTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yTopLabel.setObjectName("yTopLabel")
        self.horizontalLayout_3.addWidget(self.yTopLabel)
        self.zTopLabel = QtWidgets.QLabel(self.layoutWidget)
        self.zTopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zTopLabel.setObjectName("zTopLabel")
        self.horizontalLayout_3.addWidget(self.zTopLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.xvalLabel = QtWidgets.QLabel(self.layoutWidget)
        self.xvalLabel.setText("")
        self.xvalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xvalLabel.setObjectName("xvalLabel")
        self.horizontalLayout_6.addWidget(self.xvalLabel)
        self.yvalLabel = QtWidgets.QLabel(self.layoutWidget)
        self.yvalLabel.setText("")
        self.yvalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yvalLabel.setObjectName("yvalLabel")
        self.horizontalLayout_6.addWidget(self.yvalLabel)
        self.zvalLabel = QtWidgets.QLabel(self.layoutWidget)
        self.zvalLabel.setText("")
        self.zvalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zvalLabel.setObjectName("zvalLabel")
        self.horizontalLayout_6.addWidget(self.zvalLabel)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(CTDisplay)
        self.layoutWidget1.setGeometry(QtCore.QRect(761, 350, 151, 132))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.editButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.editButton.setObjectName("editButton")
        self.verticalLayout_5.addWidget(self.editButton)
        self.undoButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.undoButton.setObjectName("undoButton")
        self.verticalLayout_5.addWidget(self.undoButton)
        self.clearButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout_5.addWidget(self.clearButton)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.savenameLabel = QtWidgets.QLabel(CTDisplay)
        self.savenameLabel.setGeometry(QtCore.QRect(520, 660, 441, 20))
        self.savenameLabel.setText("")
        self.savenameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.savenameLabel.setObjectName("savenameLabel")
        self.layoutWidget2 = QtWidgets.QWidget(CTDisplay)
        self.layoutWidget2.setGeometry(QtCore.QRect(650, 230, 61, 47))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sliceLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.sliceLabel.setObjectName("sliceLabel")
        self.verticalLayout_2.addWidget(self.sliceLabel)
        self.slice = QtWidgets.QLineEdit(self.layoutWidget2)
        self.slice.setObjectName("slice")
        self.verticalLayout_2.addWidget(self.slice)
        self.layoutWidget3 = QtWidgets.QWidget(CTDisplay)
        self.layoutWidget3.setGeometry(QtCore.QRect(790, 290, 103, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cubelengthBox = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.cubelengthBox.setDecimals(1)
        self.cubelengthBox.setMinimum(15.6)
        self.cubelengthBox.setMaximum(46.800000000000004)
        self.cubelengthBox.setSingleStep(3.9)
        self.cubelengthBox.setObjectName("cubelengthBox")
        self.horizontalLayout_4.addWidget(self.cubelengthBox)
        self.mmLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.mmLabel.setEnabled(True)
        self.mmLabel.setObjectName("mmLabel")
        self.horizontalLayout_4.addWidget(self.mmLabel)
        self.layoutWidget4 = QtWidgets.QWidget(CTDisplay)
        self.layoutWidget4.setGeometry(QtCore.QRect(171, 581, 172, 82))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pixellimsLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.pixellimsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pixellimsLabel.setObjectName("pixellimsLabel")
        self.verticalLayout_7.addWidget(self.pixellimsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vminLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.vminLabel.setObjectName("vminLabel")
        self.verticalLayout_3.addWidget(self.vminLabel)
        self.vmaxLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.vmaxLabel.setObjectName("vmaxLabel")
        self.verticalLayout_3.addWidget(self.vmaxLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.vmin = QtWidgets.QLineEdit(self.layoutWidget4)
        self.vmin.setObjectName("vmin")
        self.verticalLayout_1.addWidget(self.vmin)
        self.vmax = QtWidgets.QLineEdit(self.layoutWidget4)
        self.vmax.setObjectName("vmax")
        self.verticalLayout_1.addWidget(self.vmax)
        self.horizontalLayout.addLayout(self.verticalLayout_1)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.statusLabel = QtWidgets.QLabel(CTDisplay)
        self.statusLabel.setGeometry(QtCore.QRect(700, 500, 261, 20))
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.layoutWidget5 = QtWidgets.QWidget(CTDisplay)
        self.layoutWidget5.setGeometry(QtCore.QRect(760, 530, 140, 100))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.saveButton = QtWidgets.QPushButton(self.layoutWidget5)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_8.addWidget(self.saveButton)
        self.segmentButton = QtWidgets.QPushButton(self.layoutWidget5)
        self.segmentButton.setObjectName("segmentButton")
        self.verticalLayout_8.addWidget(self.segmentButton)
        self.closeButton = QtWidgets.QPushButton(self.layoutWidget5)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout_8.addWidget(self.closeButton)

        self.retranslateUi(CTDisplay)
        QtCore.QMetaObject.connectSlotsByName(CTDisplay)

    def retranslateUi(self, CTDisplay):
        _translate = QtCore.QCoreApplication.translate
        CTDisplay.setWindowTitle(_translate("CTDisplay", "CT Editor"))
        self.displayButton.setText(_translate("CTDisplay", "Display"))
        self.pixelsLabel.setText(_translate("CTDisplay", "Pixels"))
        self.cubelenLabel.setText(_translate("CTDisplay", "Cube Side Length (15.6-46.9)mm:"))
        self.cubelocLabel.setText(_translate("CTDisplay", "Cube location:"))
        self.xTopLabel.setStatusTip(_translate("CTDisplay", "0"))
        self.xTopLabel.setText(_translate("CTDisplay", "x"))
        self.yTopLabel.setText(_translate("CTDisplay", "y"))
        self.zTopLabel.setText(_translate("CTDisplay", "z"))
        self.editButton.setText(_translate("CTDisplay", "Apply Edit"))
        self.undoButton.setText(_translate("CTDisplay", "Undo Edit"))
        self.clearButton.setText(_translate("CTDisplay", "Clear Edits"))
        self.sliceLabel.setText(_translate("CTDisplay", "y-slice:"))
        self.slice.setText(_translate("CTDisplay", "60"))
        self.mmLabel.setText(_translate("CTDisplay", "mm"))
        self.pixellimsLabel.setText(_translate("CTDisplay", "HU Limits"))
        self.vminLabel.setText(_translate("CTDisplay", "Min:"))
        self.vmaxLabel.setText(_translate("CTDisplay", "Max:"))
        self.vmin.setText(_translate("CTDisplay", "-400"))
        self.vmax.setText(_translate("CTDisplay", "400"))
        self.saveButton.setText(_translate("CTDisplay", "Save Scan"))
        self.segmentButton.setText(_translate("CTDisplay", "Segment Tumor"))
        self.closeButton.setText(_translate("CTDisplay", "Close"))
from mplslicewidget import MplSliceWidget
